name: progress_data_shared_preferences
description: Saves best times locally with shared_preferences.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ^3.47.0

dependencies:
  flutter:
    sdk: flutter
  progress_domain:
    path: ../progress_domain
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^11.0.0
