name: simulation_domain
description: The marble simulation interface, headless of any physics engine.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  level_domain:
    path: ../../level/level_domain
  meta: ^1.16.0
  test: ^1.31.0
  tilt_domain:
    path: ../../tilt/tilt_domain
  vector_math: ^2.1.4

dev_dependencies:
  very_good_analysis: ^11.0.0
